### ISSUE TITLE
Node Importance

### ISSUE THREAD

**Issue by FL33TW00D** [FFrankyy/FINDER#8]
Hi there,
I have read the paper and inspected all of the code in the Code Ocean.

Was there any work done on identifying which nodes in the set of key players was the most important to ANC?
I am looking for a method of ranking the solution nodes from most important to least important.

Thanks,
Chris

**Comment by fanchangjun** [comment]
Thanks for your interests! Nodes selected by Q-values are ranked naturally, those with higher Q values have larger importance.

**Comment by FL33TW00D** [comment]
Hi there,
Thank you for your response.

Looking at the Krebs graph from your paper here:
![ANC_CN](https://user-images.githubusercontent.com/45471420/87535457-71cb6700-c68f-11ea-820a-8d0343e44ea4.png)

The greatest reduction in ANC comes from the removal of the 8th node, not the first node removed. 
Did you do any work on identifying which nodes have the greatest reduction of ANC (and therefore are the most integral to overall connectivity)?

Many Thanks,
Chris

**Comment by fanchangjun** [comment]
Thanks, that's a very interesting finding. I think the reduction caused by one node is highly dependent on which nodes are removed before this node's removal, we can consider this node seperately, this is so called 'collective influence'. That's why we want to learn an optimal nodes removal sequence to minimize the area under the ANC curve.

**Comment by FL33TW00D** [comment]
@FFrankyy 
Thank you for your response.
This makes sense to me. I will use them in the order that they're outputted by FINDER and see what results I obtain. Thank you.
